window.WAYMARK_CONFIG = {
    SUPABASE_URL: 'https://YOUR_PROJECT_REF.supabase.co',
    SUPABASE_ANON_KEY: 'YOUR_SUPABASE_ANON_PUBLIC_KEY',
    AUTH_REDIRECT_URL: 'https://YOUR_DOMAIN_OR_GITHUB_PAGES_PATH/'
};
